name = "sr-investing-api"
main = "src/index.ts"
compatibility_date = "2025-08-01"
workers_dev = true

[[routes]]
pattern = "api.sr-investing.com/*"
zone_name = "sr-investing.com"

[[d1_databases]]
binding = "DB"
database_name = "sr-investing"
database_id = "60412bb1-e567-4a48-8c92-390998bd27e3"

[vars]
AUTH_EMAIL = "qianwei.shen@gmail.com"
AUTH_PASSWORD_SHA256 = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92"
ALLOWED_ORIGINS = "https://sr-investing.com,https://www.sr-investing.com,http://localhost:4321,http://127.0.0.1:4321"
